### ISSUE TITLE
OTP20037: Chojuk alignment preparation for experiments for Translation using LLm.

### ISSUE THREAD

**Issue by ta4tsering** [OpenPecha/Chojuk_data_preparation#1]
Description:
To do the experiments on translation using LLMs, I will be needing to prepare some data for the benchmarking as well as to give examples for the few-shot translation chain of thought.

Completion Criteria:
CSV with Tibetan Chojuk with alignments of translation and commentary for it.

Subtasks:

- [x] Go through the already aligned chojuk data and create csv
- [x] Create CSV for the Chojuk Commentary alignment.
- [ ] look for other chojuk translations with alignment and create CSV

Reviewer:

- [x] @tenzin3

**Comment by ta4tsering** [comment]
@tenzin3 I have send PR, kindly review it.

**Comment by tenzin3** [comment]
> [@tenzin3](https://github.com/tenzin3) I have send PR, kindly review it.

Merged
